"""Cria tabelas com os tipos corretos

Revision ID: 732b4df10bb8
Revises: 
Create Date: 2025-06-21 10:59:57.355928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '732b4df10bb8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paciente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('internacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('leito', sa.String(length=50), nullable=False),
    sa.Column('procedencia', sa.String(length=50), nullable=False),
    sa.Column('data_admissao', sa.Date(), nullable=False),
    sa.Column('data_registro', sa.DateTime(), nullable=True),
    sa.Column('reinternacao', sa.Boolean(), nullable=False),
    sa.Column('duracao_internacao', sa.String(length=50), nullable=True),
    sa.Column('local_previo', sa.String(length=255), nullable=True),
    sa.Column('terapia_cancer', sa.Boolean(), nullable=False),
    sa.Column('cancer_metastatico', sa.Boolean(), nullable=False),
    sa.Column('insuficiencia_cardiaca', sa.Boolean(), nullable=False),
    sa.Column('cirrose', sa.Boolean(), nullable=False),
    sa.Column('aids', sa.Boolean(), nullable=False),
    sa.Column('drogas_vasoativas', sa.Boolean(), nullable=False),
    sa.Column('admissao_planejada', sa.Boolean(), nullable=False),
    sa.Column('motivos_admissao', sa.String(length=255), nullable=False),
    sa.Column('cirurgia_realizada', sa.Boolean(), nullable=False),
    sa.Column('tipo_cirurgia', sa.String(length=255), nullable=True),
    sa.Column('sitio_atomico', sa.String(length=255), nullable=True),
    sa.Column('infeccao_aguda', sa.Boolean(), nullable=False),
    sa.Column('tipo_infeccao', sa.String(length=255), nullable=True),
    sa.Column('glasgow', sa.String(length=50), nullable=False),
    sa.Column('temperatura', sa.String(length=50), nullable=False),
    sa.Column('frequencia_cardiaca', sa.String(length=50), nullable=False),
    sa.Column('pressao_sistolica', sa.String(length=50), nullable=False),
    sa.Column('bilirrubina', sa.String(length=50), nullable=False),
    sa.Column('creatinina', sa.String(length=50), nullable=False),
    sa.Column('leucocitos', sa.String(length=50), nullable=False),
    sa.Column('ph', sa.String(length=50), nullable=False),
    sa.Column('plaquetas', sa.String(length=50), nullable=False),
    sa.Column('oxigenacao', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['paciente_id'], ['paciente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('internacao')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    op.drop_table('paciente')
    # ### end Alembic commands ###
