"""Aumenta tamanho dos campos texto

Revision ID: afa8c30c28ff
Revises: 732b4df10bb8
Create Date: 2025-06-21 11:06:56.544020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afa8c30c28ff'
down_revision = '732b4df10bb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('internacao', schema=None) as batch_op:
        batch_op.alter_column('motivos_admissao',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=512),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('internacao', schema=None) as batch_op:
        batch_op.alter_column('motivos_admissao',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###
