"""Adicionando dados de laudo em Internacao

Revision ID: bad1c2827232
Revises: afa8c30c28ff
Create Date: 2025-06-21 11:21:59.479733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bad1c2827232'
down_revision = 'afa8c30c28ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('internacao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('responsavel', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('desfecho', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('data_desfecho', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('destino', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('internacao', schema=None) as batch_op:
        batch_op.drop_column('destino')
        batch_op.drop_column('data_desfecho')
        batch_op.drop_column('desfecho')
        batch_op.drop_column('responsavel')

    # ### end Alembic commands ###
